import numpy as np
import numpy.typing as npt

class Resonator:
    def __init__(self, frequency: float, alpha: float, beta: float, sample_rate: float) -> None: ...
    def update_sample(self, sample: float) -> None: ...
    def update_frame(self, frame: npt.NDArray[np.float32]) -> None: ...
    def power(self) -> float: ...
    def amplitude(self) -> float: ...
    def complex(self) -> tuple[float, float]: ...
    def frequency(self) -> float: ...

def resonate_naive(
    input: npt.NDArray[np.float32],
    sample_rate: float,
    frequencies: npt.NDArray[np.float32],
    alphas: npt.NDArray[np.float32],
    betas: npt.NDArray[np.float32],
    hop_length: int,
) -> npt.NDArray[np.float32]: ...

def alpha_heuristic(
    frequencies: npt.NDArray[np.float32],
    sample_rate: float,
) -> npt.NDArray[np.float32]: ...

def midi_piano_frequencies(tuning: float) -> npt.NDArray[np.float32]: ...

def log_frequencies(fmin: float, n_bins: int, bins_per_octave: int) -> npt.NDArray[np.float32]: ...
